apiVersion: v1
kind: Secret
metadata:
  name: splunk-secret
  namespace: security-tt
type: Opaque
data:
  splunkclouduf.spl: |-
    {{SPLUNKCLOUDUF_SPL_CONTENTS_BASE64}}
  splunkescreds.txt: |-
    {{SPLUNKESCREDS_BASE64}}
